name: pyunit_evaluate

on:
  push:
    paths:
      - 'pyproject.toml'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: 下载代码
        uses: actions/checkout@master

      - name: 下载Python环境
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: 下载依赖
        run: |
          uv sync

      - name: 测试
        run: |
          uv run pytest

      - name: 构建Python包并上传到PYPI
        run: |
          uv build
          uv publish --token ${{ secrets.TOKEN }}