name: pyunit_evaluate

on:
  push:
    paths:
      - 'pyproject.toml'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: 下载代码
        uses: actions/checkout@master

      - name: 下载Python环境
        uses: actions/setup-python@master
        with:
          python-version: "3"

      - name: 下载依赖
        run: |
          python -m pip install uv
          uv sync

      - name: 测试
        run: |
          uv pip install pytest
          pytest

      - name: 构建Python包并上传到PYPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TOKEN }}
        run: |
          uv build
          twine upload dist/*.whl